/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PromiseRouteImport } from './routes/promise'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PerformanceHubRouteImport } from './routes/performance-hub'
import { Route as PartnershipsRouteImport } from './routes/partnerships'
import { Route as MissionRouteImport } from './routes/mission'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as ClutchScoreRouteImport } from './routes/clutch-score'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PerformanceHubSlugRouteImport } from './routes/performance-hub_.$slug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PromiseRoute = PromiseRouteImport.update({
  id: '/promise',
  path: '/promise',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PerformanceHubRoute = PerformanceHubRouteImport.update({
  id: '/performance-hub',
  path: '/performance-hub',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnershipsRoute = PartnershipsRouteImport.update({
  id: '/partnerships',
  path: '/partnerships',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionRoute = MissionRouteImport.update({
  id: '/mission',
  path: '/mission',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const ClutchScoreRoute = ClutchScoreRouteImport.update({
  id: '/clutch-score',
  path: '/clutch-score',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PerformanceHubSlugRoute = PerformanceHubSlugRouteImport.update({
  id: '/performance-hub_/$slug',
  path: '/performance-hub/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/clutch-score': typeof ClutchScoreRoute
  '/community': typeof CommunityRoute
  '/how-it-works': typeof HowItWorksRoute
  '/mission': typeof MissionRoute
  '/partnerships': typeof PartnershipsRoute
  '/performance-hub': typeof PerformanceHubRoute
  '/privacy': typeof PrivacyRoute
  '/promise': typeof PromiseRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/performance-hub/$slug': typeof PerformanceHubSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/clutch-score': typeof ClutchScoreRoute
  '/community': typeof CommunityRoute
  '/how-it-works': typeof HowItWorksRoute
  '/mission': typeof MissionRoute
  '/partnerships': typeof PartnershipsRoute
  '/performance-hub': typeof PerformanceHubRoute
  '/privacy': typeof PrivacyRoute
  '/promise': typeof PromiseRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/performance-hub/$slug': typeof PerformanceHubSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/clutch-score': typeof ClutchScoreRoute
  '/community': typeof CommunityRoute
  '/how-it-works': typeof HowItWorksRoute
  '/mission': typeof MissionRoute
  '/partnerships': typeof PartnershipsRoute
  '/performance-hub': typeof PerformanceHubRoute
  '/privacy': typeof PrivacyRoute
  '/promise': typeof PromiseRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/performance-hub_/$slug': typeof PerformanceHubSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/clutch-score'
    | '/community'
    | '/how-it-works'
    | '/mission'
    | '/partnerships'
    | '/performance-hub'
    | '/privacy'
    | '/promise'
    | '/sitemap.xml'
    | '/performance-hub/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/clutch-score'
    | '/community'
    | '/how-it-works'
    | '/mission'
    | '/partnerships'
    | '/performance-hub'
    | '/privacy'
    | '/promise'
    | '/sitemap.xml'
    | '/performance-hub/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/clutch-score'
    | '/community'
    | '/how-it-works'
    | '/mission'
    | '/partnerships'
    | '/performance-hub'
    | '/privacy'
    | '/promise'
    | '/sitemap.xml'
    | '/performance-hub_/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ClutchScoreRoute: typeof ClutchScoreRoute
  CommunityRoute: typeof CommunityRoute
  HowItWorksRoute: typeof HowItWorksRoute
  MissionRoute: typeof MissionRoute
  PartnershipsRoute: typeof PartnershipsRoute
  PerformanceHubRoute: typeof PerformanceHubRoute
  PrivacyRoute: typeof PrivacyRoute
  PromiseRoute: typeof PromiseRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  PerformanceHubSlugRoute: typeof PerformanceHubSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promise': {
      id: '/promise'
      path: '/promise'
      fullPath: '/promise'
      preLoaderRoute: typeof PromiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/performance-hub': {
      id: '/performance-hub'
      path: '/performance-hub'
      fullPath: '/performance-hub'
      preLoaderRoute: typeof PerformanceHubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partnerships': {
      id: '/partnerships'
      path: '/partnerships'
      fullPath: '/partnerships'
      preLoaderRoute: typeof PartnershipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mission': {
      id: '/mission'
      path: '/mission'
      fullPath: '/mission'
      preLoaderRoute: typeof MissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clutch-score': {
      id: '/clutch-score'
      path: '/clutch-score'
      fullPath: '/clutch-score'
      preLoaderRoute: typeof ClutchScoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/performance-hub_/$slug': {
      id: '/performance-hub_/$slug'
      path: '/performance-hub/$slug'
      fullPath: '/performance-hub/$slug'
      preLoaderRoute: typeof PerformanceHubSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ClutchScoreRoute: ClutchScoreRoute,
  CommunityRoute: CommunityRoute,
  HowItWorksRoute: HowItWorksRoute,
  MissionRoute: MissionRoute,
  PartnershipsRoute: PartnershipsRoute,
  PerformanceHubRoute: PerformanceHubRoute,
  PrivacyRoute: PrivacyRoute,
  PromiseRoute: PromiseRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  PerformanceHubSlugRoute: PerformanceHubSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
